name: CorePlugin
version: ${project.version}
main: com.github.lectr1c.Main
api-version: 1.16
authors: [lectr1c]
description: A core plugin that will be used on my personalized servers.
commands:
  heal:
    description: Fully heal yourself.
  gamemode:
    description: Change your gamemode.
    aliases:
      - gm
  setspawn:
  spawn:
permissions:
  core.admin:
    default: op
  core.owner:
    default: op
  core.moderator:
    default: op
  core.member:
    default: true